export const SIDENAV_RAIL_WIDTH = 56
export const SIDENAV_RAIL_GUTTER_WIDTH = 104
export const SIDENAV_RAIL_EXPANDED_WIDTH = 256
export const SIDENAV_BRAND_FIRST_TILE_WIDTH = 26
export const SIDENAV_BRAND_FULL_WIDTH = 194
export const SIDENAV_BRAND_TRAILING_WIDTH =
  SIDENAV_BRAND_FULL_WIDTH - SIDENAV_BRAND_FIRST_TILE_WIDTH
export const SIDENAV_BRAND_TRAILING_OVERLAP = 2
export const SIDENAV_RAIL_CONTENT_INSET = 10
export const SIDENAV_AUTH_CONTROL_INSET = 8
export const SIDENAV_RAIL_SIDE_OFFSET = (SIDENAV_RAIL_GUTTER_WIDTH - SIDENAV_RAIL_WIDTH) / 2
export const SIDENAV_BRAND_SIDE_OFFSET = (SIDENAV_RAIL_WIDTH - SIDENAV_BRAND_FIRST_TILE_WIDTH) / 2
export const SIDENAV_RAIL_ICON_CELL_WIDTH = SIDENAV_RAIL_WIDTH - SIDENAV_RAIL_CONTENT_INSET * 2
export const SIDENAV_RAIL_LABEL_WIDTH =
  SIDENAV_RAIL_EXPANDED_WIDTH - SIDENAV_RAIL_CONTENT_INSET * 2 - SIDENAV_RAIL_ICON_CELL_WIDTH
export const SIDENAV_AUTH_ICON_CELL_WIDTH = SIDENAV_RAIL_WIDTH - SIDENAV_AUTH_CONTROL_INSET * 2
export const SIDENAV_AUTH_LABEL_WIDTH =
  SIDENAV_RAIL_EXPANDED_WIDTH - SIDENAV_AUTH_CONTROL_INSET * 2 - SIDENAV_AUTH_ICON_CELL_WIDTH
